CREATE TABLE users (
    user_id serial,
    user_name VARCHAR(100),
    country VARCHAR(100),
    signup_date DATE,
    is_premium INT
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(255),
    category VARCHAR(100),
    price DECIMAL(10,2),
    cost DECIMAL(10,2)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    user_id INT,
    product_id INT,
    order_date DATE,
    quantity INT,
    status VARCHAR(50)
);

CREATE TABLE shipping (
    shipping_id INT PRIMARY KEY,
    order_id INT,
    ship_mode VARCHAR(50),
    shipping_fee DECIMAL(10,2),
    ship_date DATE
);

select * from orders
select * from products
select * from users
select * from shipping

-- Monthly Revenue Trend (2024 vs 2025)
WITH monthly_sales AS (
    SELECT 
        DATE_TRUNC('month', o.order_date) AS month,
        SUM(o.quantity * p.price) AS revenue
    FROM orders o
    JOIN products p ON o.product_id = p.product_id
    WHERE o.status = 'Completed'
    GROUP BY month
)
SELECT 
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month) AS prev_revenue,
    round((revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0 
        / NULLIF(LAG(revenue) OVER (ORDER BY month), 0),2) AS mom_growth_pct
FROM monthly_sales;


-- Compare the performance of each month in 2024 against the same month in 2025 to see if the business is expanding.
with monthlysales as(
     select
	 extract(month from order_date) as month_num,
	 extract(year from order_date) as order_year,
	 sum(o.quantity * p.price) as monthly_revenue
	 from orders o 
	 join products p on p.product_id = o.product_id
	 WHERE o.status = 'Completed'
	 group by 1,2
)
select
s24.month_num,
round(s24.monthly_revenue,2) as revenue_24,
round(s25.monthly_revenue,2) as revenue_25,
round((s25.monthly_revenue - s24.monthly_revenue/s24.monthly_revenue)*100,2) yoy_growth_pct
from monthlysales s24
join monthlysales s25 on s24.month_num = s25.month_num
where s24.order_year = 2024 and s25.order_year = 2025
order by s24.month_num;

-- Identify if 80% of the total revenue is generated by a small percentage (the top 20%) of your products.
with productsales as(
     select
	 p.product_id,
	 sum(o.quantity*p.price) as total_Revenue
	 from products p 
	 join orders o on o.product_id = p.product_id
	 where o.status = 'Completed'
	 group by 1
),
runningpercentage as(
   select
   product_id,
   total_revenue,
   sum(total_revenue) over(order by total_Revenue desc) /
   sum(total_revenue) over() cumulative_pct
   from productsales
)

-- Smooth out those holiday "spikes" in Nov/Dec to see the real sales trend.
select
 order_month,
 total_revenue,
 avg(total_revenue) over(order by order_month rows between 2 preceding and current row) as rolling_3pt_avg
 from(
 select
 date_trunc('month',order_date) as order_month,
 sum(quantity * price) as total_revenue
 from orders 
 join products on orders.product_id = products.product_id
 group by 1) sub;

-- Find out how much money we are losing because people cancel or return items.
SELECT
status,
sum(o.quantity * p.price) as revenue_loss
from orders o
join products p on p.product_id = o.product_id
where status != 'Completed'
group by 1;

-- Top 5 Best-Selling Categories
SELECT
category,
sum(quantity * price) as total_revenue
from orders join products on products.product_id = orders.product_id
where status ='Completed'
group by 1
order by 2 DESC
limit 5;

-- Ranking Products by Sales in Each Category
with product_rank as (
     select
	 category,
	 product_name,
	 sum(quantity) as total_sales,
	 dense_rank() over(partition by category order by sum(quantity) desc) as rn
	 from orders 
	 join products on products.product_id = orders.product_id
	 group by 1,2
)
select * from product_rank
where rn =1;

-- See how total profit builds up day by day throughout the year.
with dailyprofit as(
     select
	 order_Date,
	 sum(quantity*(price-cost)) as profit
	 from orders join products 
	 on products.product_id = orders.product_id
	 where status = 'Completed'
	 group by 1
)
SELECT
order_date,
profit,
sum(profit) over(partition by order_Date) as running_total_profit
from dailyprofit;


-- Comparing Individual Orders to the Average
WITH OrderTotals AS (
    SELECT 
        order_id,
        SUM(quantity * price) AS total_order_value
    FROM orders o
    JOIN products p ON o.product_id = p.product_id
    GROUP BY 1
)
SELECT 
    order_id,
    total_order_value,
    AVG(total_order_value) OVER () AS global_avg_order
FROM OrderTotals
WHERE total_order_value > (SELECT AVG(quantity * price) FROM orders o JOIN products p 
                           ON o.product_id = p.product_id) * 2;

-- See if today's sales are better than yesterday's using a Window Function.
with daily_sales as(
      select 
	  order_date,
	  sum(quantity * price) as daily_revenue
	  from orders join products on products.product_id = orders.product_id
	  group by 1
)
SELECT
order_Date,
daily_revenue,
lag(daily_revenue) over(order by order_date) as yesterday_revenue,
daily_revenue - lag(daily_revenue) over(order by order_date) as daily_diff
from daily_sales;

-- Identify customers who placed an order in 2024 but have zero orders in 2025. This helps the marketing team target "lost" customers.
SELECT
user_id,user_name
from users
where user_id in (
     select user_id from orders where extract(year from order_date) = 2024
)
and user_id not in(
    select user_id from orders where extract(year from order_date) = 2025
);

-- Find out what percentage of your customers are "Loyal" (ordered more than 3 times) compared to the average.
with loyalcustomers as(
     select
	 user_id,
	 count(order_id) as order_count
	 from orders
	 group by user_id
)
select
order_count,
count(user_id) as total_customers,
sum(count(user_id)) over() as global_total_user,
round(count(user_id)*100.0/sum(count(user_id)) over(),2) as percent
from loyalcustomers
group by order_count
order by order_count desc;

-- Find orders that took longer than the average shipping time of their specific ship_mode.
with shiptime as(
     select
	 o.order_id,
	 s.ship_mode,
	 (s.ship_date - o.order_date) as days_To_ship
	 from orders o
	 join shipping s on o.order_id = s.order_id
)

select * from shiptime st
where days_To_ship > (
    select avg(days_To_ship)
	from shiptime stt
	where st.ship_mode = stt.ship_mode
)
limit 10;

-- Find products that have never been ordered. These are "dead stock" taking up space in your database.
SELECT product_id, product_name, category
FROM products
WHERE product_id NOT IN (
    SELECT DISTINCT product_id FROM orders
);
